import Head from 'next/head'
import { Inter } from 'next/font/google'
import { useRouter } from 'next/router';

import {useEffect} from "react";
import AddressList from "@/pages/address/addressList";
import {useSelector} from "react-redux";

export default function Home() {
    const user = useSelector(state => state.user.user)
    const router = useRouter();

    useEffect(() => {
        if (!user) {
            router.push('/auth/login');
        }

    }, [user]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
         <AddressList />
      </main>
    </>
  )
}
